server:
  port: 9400
  servlet:
    context-path: /product

spring:
  # \u73AF\u5883 dev|test|prod
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto