server:
  port: 7200
spring:
  application:
    name: gulimail-eureka-consume
eureka:
  client:
    service-url:
      defaultZone: http://eureka7000.com:7000/eureka,http://eureka7001.com:7001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true