server:
  port: 9100
  servlet:
    context-path: /coupon
spring:
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        #注册地址
        server-addr: https://nacos.huaxia.city

      #应用名称
  application:
    name: gulimail-coupon
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto


