server:
  port: 9300
  servlet:
    context-path: /order

spring:
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto