spring:
  cloud:
    nacos:
      discovery:
        server-addr: https://nacos.huaxia.city
    gateway:
      globalcors:
        #跨域配置 参考 https://cloud.spring.io/spring-cloud-gateway/2.2.x/reference/html/#cors-configuration
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

